In [2]:
import numpy as np
import tkinter

root = tkinter.Tk()
(m,n) = (20,20)
border_color = tkinter.Frame(root, background="red")
matrix = np.zeros((m,n))
for i in range(n):
    for j in range(m):
        text = tkinter.Label(root,text='', height=1,width=3,foreground='black',background='green',bd=2,relief="solid")
        text.grid(row=i,column=j)
# border_color.pack(padx=40,pady=40)
root.mainloop()

In [3]:
def move(mode=0):
    if(mode==0):
        step = np.random.randint(1,5)
        if(step==1): (x,y)=(1,0)
        elif(step==2): (x,y)=(-1,0)
        elif(step==3): (x,y)=(0,1)
        else: (x,y)=(0,-1)
        return (x,y)
    elif(mode==1): return (1,0)
    elif(mode==2):return (0,1)
    elif(mode==3):return (0,-1)
    else: return(-1,0)

test = np.zeros((m,n),dtype='uint8')
test[0,0]=1
cordx = 0
cordy = 0
count = 0
while(count<70):
    for i in range(128):
        (x,y) = move()
        repeat = 0
        while(cordx+x<0 or
            cordx+x>=m or
            cordy+y<0 or
            cordy+y>=n or
            test[cordx+x,cordy+y]!=0):
            (x,y) = move(mode=repeat)
            repeat+=1
            if(repeat>=5): break
        if(repeat>=5): break
        count = test[cordx,cordy]+1
        cordx = cordx + x
        cordy = cordy + y
        # print(cordx,' ',cordy)
        test[cordx,cordy]=count
print(count)
print(test)

KeyboardInterrupt: 

In [10]:
def findpath(matrix,x0,y0,x1,y1):
    if(x1<x0): step = 1
    elif(x1>x0):step = -1
    else: step = 0
    while(x1!=x0 and step != 0): 
        x1=x1+step
        matrix[x1,y1]=1
    if(y1<y0): step = 1
    elif(y1>y0):step = -1
    else: step = 0
    while(y1!=y0 and step != 0): 
        y1=y1+step
        matrix[x1,y1]=1
    return matrix

(m,n) = (20,20)
matrix = np.zeros((m,n),dtype='uint8')
matrix[0,0]=1
matrix[m-1,n-1]=1
oldx=0
oldy=0
for i in range(25):
    x = np.random.randint(0,m)
    y = np.random.randint(0,n)
    matrix = findpath(matrix,x,y,oldx,oldy)
    oldx=x
    oldy=y
matrix = findpath(matrix,oldx,oldy,m-1,n-1)
# print(matrix,'\n')
# for i in range(m-2):
#     for j in range(n-2):
#         if(np.count_nonzero(matrix[i:i+3,j:j+3])>=9):
#             # matrix[i:i+3,j:j+3]=0
#             matrix[i,j]=0
#             matrix[i+2,j]=0
#             matrix[i,j+2]=0
#             matrix[i+2,j+2]=0
# print(matrix,'\n')
# for i in range(m-1):
#     for j in range(n-1):
#         if(np.count_nonzero(matrix[i:i+2,j:j+2])>=4):
#             x = np.random.randint(0,2)
#             y = np.random.randint(0,2)
#             matrix[i+x,j+y]=0
print(matrix)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]
 [1 1 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1]
 [0 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 1 0 1 0 0 1 0 0 0 0 0 1 1 1 1 1 1 1 1]
 [0 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 1 0 1 0 0 1 1 0 0 0 0 1 1 0 1 1 1 1 1]
 [0 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 1 0 1 1 1 1 1 0 0 0 0 1 1 0 0 1 1 1 1]
 [0 1 0 0 0 1 1 0 0 0 0 0 1 1 0 0 1 1 1 1]
 [0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1]
 [0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1]
 [0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1]
 [0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]


In [47]:
m = np.zeros((18,15),dtype='uint8')

def setRandomPath(matrix,x0,y0):
    (h,l) = matrix.shape
    if(np.random.randint(1,3)==1):
        for i in range(x0,np.random.randint(x0,l)):matrix[i][y0]=1
    else: 
        for i in range(y0,np.random.randint(y0,h)):matrix[x0][i]=1

print(setRandomPath(m,2,3))


None


In [48]:
import numpy as np
from tkinter import W


class node():
    def __init__(self,x,y):
        self.x=x
        self.y=y
        self.connections = []
    def connect(self,newnode):
        if(len(self.connections)>0):
            for i in self.connections:
                if(i.x == newnode.x and i.y == newnode.y):return
        
        if((self.x == newnode.x + 1 or self.x == newnode.x - 1) and self.y == newnode.y):
            self.connections.append(newnode)
            newnode.connections.append(self)
            return
        if((self.y == newnode.y + 1 or self.y == newnode.y - 1) and self.x == newnode.x):
            self.connections.append(newnode)
            newnode.connections.append(self)
            return
def randomConnection(grid):
    (w,h) = grid.shape
    x = np.random.randint(0,w)
    y = np.random.randint(0,h)
    neighbor = np.random.randint(0,4)
    if(neighbor==0 and x>0):
        grid[x,y].connect(grid[x-1,y])
        return
    elif(neighbor==1 and x<w-1):
        grid[x,y].connect(grid[x+1,y])
        return
    elif(neighbor==2 and y>0):
        grid[x,y].connect(grid[x,y-1])
        return
    elif(y<h-1):
        grid[x,y].connect(grid[x,y+1])
        return
def fillAll(grid):
    (w,h) = grid.shape
    flag = False
    while(flag==False):
        flag=True
        for i in range(w):
            for j in range(h):
                if(len(grid[i,j].connections)<=0):
                    flag=False
                    neighbor = np.random.randint(0,4)
                    if(neighbor==0 and i>0):
                        grid[i,j].connect(grid[i-1,j])
                    elif(neighbor==1 and i<w-1):
                        grid[i,j].connect(grid[i+1,j])
                    elif(neighbor==2 and j>0):
                        grid[i,j].connect(grid[i,j-1])
                    elif(j<h-1):
                        grid[i,j].connect(grid[i,j+1])




In [52]:
(w,h) = (50,50)
grid = np.full((h,w),fill_value=node(0,0))
for i in range(h):
    for j in range(w):
        grid[i,j]=node(i,j)


for i in range(int(w*h*1.8)): randomConnection(grid=grid)
fillAll(grid=grid)

matrix = np.zeros((h,w),dtype='uint8')
for i in range(h):
    for j in range(w):
        matrix[i,j]=len(grid[i,j].connections)
print(matrix)

maze = np.zeros((h*2-1,w*2-1),dtype='uint8')
# maze=maze+1
for i in range(h*2-1):
    for j in range(w*2-1):
        if(i&1==1 or j&1==1):maze[i,j]=1

print(maze)

[[2 3 3 ... 2 2 1]
 [2 4 3 ... 1 2 3]
 [1 4 2 ... 1 3 2]
 ...
 [1 4 3 ... 3 2 1]
 [2 4 2 ... 2 3 2]
 [2 3 1 ... 2 3 2]]
[[0 1 0 ... 0 1 0]
 [1 1 1 ... 1 1 1]
 [0 1 0 ... 0 1 0]
 ...
 [0 1 0 ... 0 1 0]
 [1 1 1 ... 1 1 1]
 [0 1 0 ... 0 1 0]]


In [53]:
from IPython.display import clear_output
for i in range(h):
    for j in range(w):
        for k in range(len(grid[i,j].connections)):
            if(grid[i,j].x==grid[i,j].connections[k].x):
                if(grid[i,j].y==grid[i,j].connections[k].y+1): maze[i*2,j*2-1]=0
                else: maze[i*2,j*2+1]=0
            else: 
                if(grid[i,j].x==grid[i,j].connections[k].x+1): maze[i*2-1,j*2]=0
                else: maze[i*2+1,j*2]=0
            clear_output(wait=False)
            # print(maze)

[[0 0 0 ... 0 1 0]
 [0 1 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]


In [55]:
import cv2
truemaze=maze*255
truemaze=255-truemaze
truemaze=cv2.resize(truemaze,(600,600),interpolation=0)
_,truemaze = cv2.threshold(truemaze,127,255,type=0)

cv2.imshow('maze',truemaze)
cv2.waitKey(0)
cv2.destroyAllWindows()