In [1]:
# Init the Gird components and functions
import numpy as np
from tkinter import W


class node():
    def __init__(self,x,y):
        self.x=x
        self.y=y
        self.connections = []
    def connect(self,newnode):
        if(len(self.connections)>0):
            for i in self.connections:
                if(i.x == newnode.x and i.y == newnode.y):return
        
        if((self.x == newnode.x + 1 or self.x == newnode.x - 1) and self.y == newnode.y):
            self.connections.append(newnode)
            newnode.connections.append(self)
            return
        if((self.y == newnode.y + 1 or self.y == newnode.y - 1) and self.x == newnode.x):
            self.connections.append(newnode)
            newnode.connections.append(self)
            return
def randomConnection(grid):
    (w,h) = grid.shape
    x = np.random.randint(0,w)
    y = np.random.randint(0,h)
    neighbor = np.random.randint(0,4)
    if(neighbor==0 and x>0):
        grid[x,y].connect(grid[x-1,y])
        return
    elif(neighbor==1 and x<w-1):
        grid[x,y].connect(grid[x+1,y])
        return
    elif(neighbor==2 and y>0):
        grid[x,y].connect(grid[x,y-1])
        return
    elif(y<h-1):
        grid[x,y].connect(grid[x,y+1])
        return
def fillAll(grid):
    (w,h) = grid.shape
    flag = False
    while(flag==False):
        flag=True
        for i in range(w):
            for j in range(h):
                if(len(grid[i,j].connections)<=0):
                    flag=False
                    neighbor = np.random.randint(0,4)
                    if(neighbor==0 and i>0):
                        grid[i,j].connect(grid[i-1,j])
                    elif(neighbor==1 and i<w-1):
                        grid[i,j].connect(grid[i+1,j])
                    elif(neighbor==2 and j>0):
                        grid[i,j].connect(grid[i,j-1])
                    elif(j<h-1):
                        grid[i,j].connect(grid[i,j+1])




In [47]:
# Init the grid
(w,h) = (30,30)
grid = np.full((h,w),fill_value=node(0,0))
for i in range(h):
    for j in range(w):
        grid[i,j]=node(i,j)


for i in range(int(w*h*1.6)): randomConnection(grid=grid)
for i in range(int(w*h/15)): randomConnection(grid=grid[0:int(w/3),0:int(h/3)])
for i in range(int(w*h/15)): randomConnection(grid=grid[int(2*w/3):w,int(2*h/3):h])
fillAll(grid=grid)

matrix = np.zeros((h,w),dtype='uint8')
for i in range(h):
    for j in range(w):
        matrix[i,j]=len(grid[i,j].connections)
print(matrix)

maze = np.zeros((h*2-1,w*2-1),dtype='uint8')
# maze=maze+1
for i in range(h*2-1):
    for j in range(w*2-1):
        if(i&1==1 or j&1==1):maze[i,j]=1

print(maze)

[[2 3 3 3 3 3 3 3 3 2 2 3 1 1 1 2 1 1 2 2 2 1 1 3 2 2 2 2 3 2]
 [2 3 4 2 3 2 2 4 4 4 2 2 3 2 1 3 1 3 4 2 2 2 1 3 1 3 3 1 4 3]
 [1 3 2 1 4 2 2 4 4 4 1 2 4 3 1 1 3 4 3 3 1 1 2 2 2 3 2 1 1 2]
 [2 4 2 3 4 3 3 2 3 4 2 2 3 1 3 1 1 1 2 4 3 2 2 1 1 2 3 2 1 3]
 [3 4 2 3 2 2 3 3 3 4 4 2 4 3 3 1 2 2 2 2 1 1 2 2 2 2 1 1 1 1]
 [2 2 1 4 3 3 2 2 2 4 3 2 2 3 2 4 4 4 3 2 1 2 2 2 3 2 2 2 1 1]
 [3 3 1 3 2 3 2 1 3 3 1 2 3 3 1 2 3 3 1 2 2 2 2 4 3 2 3 4 2 1]
 [2 3 2 4 3 2 3 2 1 4 2 2 4 3 1 2 4 4 3 2 1 2 2 2 4 3 4 4 3 1]
 [2 3 3 3 2 2 3 3 2 3 3 3 4 2 2 1 2 3 3 2 3 3 3 3 4 3 3 1 2 1]
 [2 3 2 2 3 3 3 2 3 2 2 2 2 2 3 3 4 3 3 1 2 4 1 3 3 3 3 1 1 1]
 [1 2 1 2 1 2 1 1 2 3 1 3 2 2 3 4 4 1 1 1 2 3 2 3 2 1 3 3 2 2]
 [1 2 1 3 2 3 3 3 3 2 3 3 2 2 4 3 2 2 2 2 1 3 3 1 2 1 2 3 4 3]
 [1 2 2 2 2 3 3 1 2 1 3 2 2 2 2 3 1 1 2 2 1 3 4 1 1 2 1 2 2 3]
 [2 2 3 4 4 4 2 1 2 1 3 1 2 1 1 2 1 2 2 2 1 3 4 2 3 4 2 3 1 3]
 [2 3 2 1 1 1 1 1 4 2 3 3 2 2 1 2 2 1 2 3 2 2 4 2 3 3 3 4 3 3]
 [1 2 2 1 1 2 3 2 3 3 2 3 1 3 1 3 4 3 3 2 2 1 2 2 2 2 1

In [48]:
# Convert Grid to data of maze
from IPython.display import clear_output
for i in range(h):
    for j in range(w):
        for k in range(len(grid[i,j].connections)):
            if(grid[i,j].x==grid[i,j].connections[k].x):
                if(grid[i,j].y==grid[i,j].connections[k].y+1): maze[i*2,j*2-1]=0
                else: maze[i*2,j*2+1]=0
            else: 
                if(grid[i,j].x==grid[i,j].connections[k].x+1): maze[i*2-1,j*2]=0
                else: maze[i*2+1,j*2]=0
            clear_output(wait=False)
            # print(maze)

In [49]:
import cv2
truemaze=maze*255
truemaze=255-truemaze
truemaze=cv2.resize(truemaze,(600,600),interpolation=0)
# _,truemaze = cv2.threshold(truemaze,127,255,type=0)

cv2.imshow('maze',truemaze)
cv2.waitKey(0)
cv2.destroyAllWindows()